#Database Properties(For config server impl)
spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
spring.datasource.username=postgres
spring.datasource.password=root

#Config service registry url
eureka.client.service-url.defaultZone=http://localhost:8761/registry/eureka
